coverage:
  status:
    project:
      web:
        target: auto
        flags:
          - web
      mobile:
        target: auto
        flags:
          - mobile
comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null
flags:
  web:
    paths:
      - packages/web/coverage.txt
    carryforward: true
  mobile:
    paths:
      - packages/mobile/coverage.txt
    carryforward: true
