name: Codecov Coverage
on: [push]
jobs:
  run:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Node  
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: Generate coverage report
      run: |
        yarn install
        yarn test
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        yml: ./codecov.yml 
        fail_ci_if_error: true
